apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: formbricks
  name: formbricks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: formbricks
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: formbricks
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/formbricks?schema=public
            - name: EMAIL_VERIFICATION_DISABLED
              value: "1"
            - name: PASSWORD_RESET_DISABLED
              value: "1"
          image: ghcr.io/formbricks/formbricks:latest
          name: formbricks
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /home/nextjs/apps/web/uploads
              name: uploads
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads
